name: Publish-Docs
on: 
  push:
    branches:
      - master
jobs:
  publish-docs:
    name: Publish documentation to netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build-docs
      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs
        env:
          NETLIFY_SITE_ID: mhocawscredreportts
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}